### ISSUE TITLE
Missing translations for a language keep spamming error log

### ISSUE THREAD

**Issue by jurchiks** [kartik-v/yii2-password#57]
I get a TON of this error message in my error logs, which really makes it hard to find actual problems in the error log, since they drown in the sea of these:

>The message file for category 'kvpwdstrength' does not exist: /var/www/{project-name}/vendor/kartik-v/yii2-password/messages/uk/kvpwdstrength.php

You don't have a Ukrainian translation, so the message is understandable, but the fact that it spams so much is not, which is why I'd like to use the Russian translation instead. How could I do this?

**Comment by kartik-v** [comment]
Best is if you could submit a Pull Request for Ukranian translation to be added to the extension.

Alternatively, you can set the language property for the widget to Russian.

**Comment by jurchiks** [comment]
Yeeah, I don't know any Ukrainian...
Does that mean EVERY widget everywhere in the site has to have this property set?

**Comment by jurchiks** [comment]
Also, how exactly do you set the language property? I can't find any documentation for that and there is no reference to "lang" in the StrengthValidator class.

**Comment by jurchiks** [comment]
FYI, StrengthValidator's property `$_msgCat` is not used anywhere for some reason.

**Comment by kartik-v** [comment]
You can set it globally via your yii2 application config that will be automatically read by the widget (which is what you must be doing to set Ukranian).

Only if you need different language for the widget (different from your yii2 app language) - then you can use the widget's language property.

Since `kartik\password\PasswordInput` extends `kartik\base\InputWidget` you can refer the [`language` property documented there](https://github.com/kartik-v/yii2-krajee-base/blob/master/InputWidget.php#L54-L60).

**Comment by jurchiks** [comment]
That is what I need, since the frontend's language can be Ukrainian for the users.
So there is no way to set your widget's language globally, so I don't have to change every place where your widget is used?

**Comment by jurchiks** [comment]
Obtained the translations, could you merge this? https://github.com/kartik-v/yii2-password/pull/58
