### ISSUE TITLE
Strong password problem

### ISSUE THREAD

**Issue by sagittaracc** [kartik-v/yii2-password#80]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of yii2-password.
- [ ] This is not an usage question. I confirm having gone through and read the [documentation and demos](http://demos.krajee.com/password-details/password-input).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Type in the password "aaaaaaaaaaaaa"

## Expected behavior and actual behavior

Expected: it says the password is weak
Actual: it says the password is strong

When I follow those steps, I see...

I was expecting...

#### Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [ ] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

#### Libraries

- jQuery version:
- yii2-password version:

## Isolating the problem

- [ ] This bug happens [on the demos page](http://demos.krajee.com/password-details/password-input)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-password without other plugins.

**Comment by kartik-v** [comment]
Currently character repetitions are not part of the password strength check. This is logical because password strengths are designed for digital password hackers which look at combination of factors and length of the password even with repetitive characters technically increases strength of the password.

However, will note a potential enhancement for this for including a validation to check for max allowed repeat characters. This will not alter the strength check but directly give a password validation error if more than N characters are repeated.

**Comment by ravitwaytoweb** [comment]
I am using password input widget for strong password with meter in customer module for save strong customer password but i got error like : Password cannot contain more than 4 repeating characters! 

Is it possible to disabled this warning message ?
